version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/node:10.15.1

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout

            - run:
                  name: Print node, npm and yarn versions
                  command: node -v && npm -v && yarn -v

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: Install web page dependencies
                  command: yarn install

            - run:
                  name: Install functions dependencies
                  command: cd functions && yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

                  # run tests!
            - run:
                  name: Run tests
                  command: yarn test

            - run:
                  name: Build application
                  command: yarn build

            - run:
                  name: Deploy Master to Firebase
                  command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project=$FIREBASE_PROJECT_ID
